baseURL = "http://example.org"
languageCode = "fr-FR"
title = "Mon super site"
theme = "ananke"

[params]
    featured_image = "/images/namibie.jpg"
    recent_posts_number = 0
    mainSections = ["content"]