baseURL = "https://mon-super-site-a-moi.netlify.com"
languageCode = "fr-FR"
title = "Mon site à moi"
theme = "ananke"

[params]
    featured_image = "/images/namibie.jpg"
    recent_posts_number = 0
    mainSections = ["content"]